# Generated by Django 4.2.5 on 2023-12-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testoptilab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='fichier_excel',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
