# Generated by Django 4.2.5 on 2023-12-10 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('testoptilab', '0002_fichier_fichier_excel_alter_fichier_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='calibre',
            field=models.CharField(default='default_calibre', max_length=50),
        ),
        migrations.AddField(
            model_name='fichier',
            name='id_compteur',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='lib_compteur',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichier',
            name='nom_bd',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichier',
            name='num_compteur',
            field=models.CharField(default=3, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichier',
            name='source',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichier',
            name='unité',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
    ]
