# Generated by Django 4.2.5 on 2023-12-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testoptilab', '0004_rename_unité_fichier_unite_alter_fichier_id_compteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichier',
            name='calibre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='id_compteur',
            field=models.IntegerField(),
        ),
    ]
