# Generated by Django 4.2.5 on 2023-12-11 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testoptilab', '0005_alter_fichier_calibre_alter_fichier_id_compteur'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='moyenne',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='nbre_case',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='pas_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='pas_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='total_consomation1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='total_consommation2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='total_consommation_jou1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='total_consommation_jour2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fichier',
            name='valeur_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fichier',
            name='calibre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Calcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vecteur_pas1', models.FloatField(blank=True, null=True)),
                ('vecteur_pas2', models.FloatField(blank=True, null=True)),
                ('consommation_pas1', models.FloatField(blank=True, null=True)),
                ('consommation_pas2', models.FloatField(blank=True, null=True)),
                ('consommation_jour1', models.FloatField(blank=True, null=True)),
                ('consommation_jour2', models.FloatField(blank=True, null=True)),
                ('fichier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testoptilab.fichier')),
            ],
        ),
    ]
