# Generated by Django 4.2.5 on 2023-12-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testoptilab', '0006_fichier_max_fichier_min_fichier_moyenne_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichier',
            old_name='total_consomation1',
            new_name='total_consommation1',
        ),
        migrations.RenameField(
            model_name='fichier',
            old_name='total_consommation_jou1',
            new_name='total_consommation_jour1',
        ),
        migrations.RemoveField(
            model_name='calcul',
            name='consommation_jour1',
        ),
        migrations.RemoveField(
            model_name='calcul',
            name='consommation_jour2',
        ),
        migrations.RemoveField(
            model_name='calcul',
            name='consommation_pas1',
        ),
        migrations.RemoveField(
            model_name='calcul',
            name='consommation_pas2',
        ),
        migrations.RemoveField(
            model_name='calcul',
            name='vecteur_pas1',
        ),
        migrations.RemoveField(
            model_name='calcul',
            name='vecteur_pas2',
        ),
        migrations.AlterField(
            model_name='fichier',
            name='calibre',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='LigneCalcul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vecteur_pas1', models.FloatField(blank=True, null=True)),
                ('vecteur_pas2', models.FloatField(blank=True, null=True)),
                ('consommation_pas1', models.FloatField(blank=True, null=True)),
                ('consommation_pas2', models.FloatField(blank=True, null=True)),
                ('consommation_jour1', models.FloatField(blank=True, null=True)),
                ('consommation_jour2', models.FloatField(blank=True, null=True)),
                ('calcul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testoptilab.calcul')),
            ],
        ),
    ]
