# Generated by Django 4.2.5 on 2023-12-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testoptilab', '0009_lignecalcul_consommation_annee1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='total_consommation_heure1',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
