# Generated by Django 4.2.5 on 2023-12-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testoptilab', '0010_fichier_total_consommation_heure1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichier',
            name='filtered_data_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
